CREATE TABLE IF NOT EXISTS student (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    course VARCHAR(255)
);
INSERT INTO student (name, email, course) VALUES ('Rishi Srivastava', 'rishi@example.com', 'B.Tech CSE');
INSERT INTO student (name, email, course) VALUES ('Meenakshi Gupta', 'meenakshi@example.com', 'AI/ML');